spring.application.name=restapi
spring.datasource.url=jdbc:postgresql://localhost:5432/MyApiDB
spring.datasource.username=postgres
spring.datasource.password=stud
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
application.security.jwt.secret-key=7aab3384a904886d6b677dd3ce3fbaec731642bf7fc80f6254be3b283efb4be7
# JWT token expiration 12 minutes
application.security.jwt.expiration=720000
# Refresh token expiration
application.security.jwt.refresh-token.expiration=86400000