spring.profiles.active=local
spring.application.name=restapi
spring.datasource.url=jdbc:postgresql://localhost:5432/MyApiDB
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.error.include-message=always
# JWT token expiration 12 minutes
application.security.jwt.expiration=72000
# Refresh token expiration
application.security.jwt.refresh-token.expiration=86400000
tmdb.api.key=${TMDB_API_KEY}