spring.application.name=restapi
spring.datasource.url=jdbc:postgresql://localhost:5432/MyApiDB
spring.datasource.username=postgres
spring.datasource.password=stud
spring.jba.hibernate.ddl-auto=create-drop
spring.jba.show-sql=true
spring.jba.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jba.properties.hibernate.format_sql=true
